Add ast parser
bragov4ik/yacal pull request #8
Opened 2022-02-06 16:01 UTC by i1i1

2022-02-06 16:26 UTC, Ilya-Kolomin requested changes
Один момент меня смутил, все остальное вроде неплохо выглядит.

2022-02-06 16:26 UTC, Ilya-Kolomin commented on pkg/parser/parser.go
> +		return nil, pp.Errorf("Expected some element, but got %v", p.lex.Eat().Value)
Скорее всего надо заменить на `return l.lex.Peek(), pp.Errorf("Expected some element, but got %v", p.lex.Eat().Value)`, а то ошибка не отработает

2022-02-06 16:31 UTC, i1i1 commented on pkg/parser/parser.go
> +		return nil, pp.Errorf("Expected some element, but got %v", p.lex.Eat().Value)
Так ты должен возвратить элемент дерева, а ты будешь возвращать токен тут. Допустим на какую лексему ты замапишь токен `)`?

2022-02-06 16:35 UTC, Ilya-Kolomin commented on pkg/parser/parser.go
> +		return nil, pp.Errorf("Expected some element, but got %v", p.lex.Eat().Value)
Ну тут бага, что если у тебя вся программа это `)`, то `Parse()` не отработает должным образом. Посмотри сам, он увидит, что `e == nil` на 76 строке и вернет программу без ошибки.

2022-02-06 16:36 UTC, Ilya-Kolomin commented on pkg/parser/parser.go
> +		return nil, pp.Errorf("Expected some element, but got %v", p.lex.Eat().Value)
Может имеет смысл поменять там проверки

2022-02-06 17:42 UTC, i1i1 commented on pkg/parser/parser.go
> +		return nil, pp.Errorf("Expected some element, but got %v", p.lex.Eat().Value)
Поправил баг отдельным коммитом

2022-02-06 17:42 UTC, Ilya-Kolomin approved these changes

2022-02-06 19:46 UTC, sevenzing approved these changes

2022-02-06 21:41 UTC, bragov4ik commented on pkg/parser/ast/ast.go
> +	List   []interface{}
Не лучше будет сделать интерфейс из которого сделать потом struct'ы, чтобы потом было проще и понятнее различать всякие литералы/типы? Как в go/ast
```

2022-02-06 21:57 UTC, bragov4ik requested changes

2022-02-06 21:57 UTC, bragov4ik commented on pkg/parser/parser_test.go
> +	}
```suggestion
		parsesTo(`(setq x 5)
			(setq y (plus 1 2))
			(setq z null)`, list(
			list(atom("setq"), atom("x"), 5),
			list(atom("setq"), atom("y"), list(atom("plus"), 1, 2)),
			list(atom("setq"), atom("z"), ast.Null{}),
		)),
	}
```
Infinite loop in this test case

2022-02-07 09:45 UTC, i1i1 commented on pkg/parser/ast/ast.go
> +	List   []interface{}
Там нужно будет делать явные конверсии тогда. По факту тут интерфейс будет выступать маркером/enum-ом. По моему это просто костыль и стоит забить и сделать просто нетипизированно.

2022-02-09 07:35 UTC, merged